---
title: "Assignment_3"
author: "Patrik Molnar"
date: '2022-11-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r stup}
pacman::p_load(glue,
       tidyr,
       data.table,
       moments,
       tidybayes,
       tibble,
       cowplot,
       viridis,
       brms,
       rstan,
       cmdstanr,
       magrittr,
       gridExtra,
       grid,
       lattice,
       ggplot2,
       ggridges,
       ellipse,
       Rmisc, 
       dplyr, 
       "rmarkdown", 
       knitr)
pacman::p_load(tidyverse)
pacman::p_load(purr)
pacman::p_load(splitstackshape)
pacman::p_load(tidymodels)
```

```{r}
###Data simulation 
n <- 100
trials <- 10

#Effect sizes definition = Informed effect mean and Skeptic effect mean
IEM <- c(-0.5,-1.26,-.74,1.89,0.25,1.3,0,0,0,0)
SEM <- rep(0,10)

#Defining individual vairability from populationd accross trials measurement error
ISD <- 1
TSD <- 0.5
E <- 0.2

```

```{r}
for (i in seq(10)){
  temp_informed <- tibble(
    ID=seq(n),
    TrueEffect = rnorm(n, IEM[i], ISD),
    Variable = paste0("V",i))
  temp_skeptic <- tibble(
    ID=seq(n),
    TrueEffect = rnorm(n, SEM[i], ISD),
    Variable = paste0("V",i))
  
  if(i==1){
    d_informed_true <- temp_informed
    d_skeptic_true <- temp_skeptic
  } else {
    d_informed_true <-  rbind(d_informed_true, temp_informed)
    d_skeptic_true <- rbind(d_skeptic_true, temp_skeptic)
  }
}
```

```{r}
d_trial <- tibble(expand_grid(ID=seq(n), Trial = seq(trials), Group = c("Schizophrenia", "Control")))

d_informed <- merge(d_informed_true, d_trial)
d_skeptic <- merge(d_skeptic_true, d_trial)

for ( i in seq(nrow(d_informed))){
  d_informed$measurement[i] <- ifelse(d_informed$Group[i]=="Schizophrenia",
                                      rnorm(1, rnorm(1, d_informed$TrueEffect[i]/2, TSD), E),
                                      rnorm(1, rnorm(1, (-d_informed$TrueEffect[i])/2, TSD), E))
  
  d_skeptic$measurement[i] <- ifelse(d_skeptic$Group[i]=="Schizophrenia",
                                      rnorm(1, rnorm(1, d_skeptic$TrueEffect[i]/2, TSD), E),
                                      rnorm(1, rnorm(1, (-d_skeptic$TrueEffect[i])/2, TSD), E))
}
```

```{r}
d_informed_wide <- d_informed %>% 
  mutate(TrueEffect=NULL) %>% 
  pivot_wider(names_from = Variable,
              values_from = measurement)
d_skeptic_wide <- d_skeptic %>% 
  mutate(TrueEffect=NULL) %>% 
  pivot_wider(names_from = Variable,
              values_from = measurement)
```


### Visualizing the simulated data for informed data frame
```{r}
plot1 <- d_informed_wide %>% 
  ggplot(aes(x = v1, color = group))+
  geom_density()

plot2 <- d_informed_wide %>% 
  ggplot(aes(x = v2, color = group))+
  geom_density()

plot3 <- d_informed_wide %>% 
  ggplot(aes(x = v3, color = group))+
  geom_density()

plot4 <- d_informed_wide %>% 
  ggplot(aes(x = v4, color = group))+
  geom_density()

plot5 <- d_informed_wide %>% 
  ggplot(aes(x = v5, color = group))+
  geom_density()

plot6 <- d_informed_wide %>% 
  ggplot(aes(x = v6, color = group))+
  geom_density()

plot7 <- d_informed_wide %>% 
  ggplot(aes(x = v7, color = group))+
  geom_density()

plot8 <- d_informed_wide %>% 
  ggplot(aes(x = v8, color = group))+
  geom_density()

plot9 <- d_informed_wide %>% 
  ggplot(aes(x = v9, color = group))+
  geom_density()

plot10 <- d_informed_wide %>% 
  ggplot(aes(x = v10, color = group))+
  geom_density()

cowplot::plot_grid(plot1, plot2, plot3, plot4, plot5, plot6, plot7, plot8, plot9, plot10, 
          labels = c("v1", "v2", "v3",'v4','v5','v6','v7','v8','v9','v10'),
          ncol = 5, nrow = 2)


```

### Visualizing the simulated data for skeptical data frame
```{r}
plot1_s <- d_skeptic_wide %>% 
  ggplot(aes(x = v1, color = group))+
  geom_density()

plot2_s <- d_skeptic_wide %>% 
  ggplot(aes(x = v2, color = group))+
  geom_density()

plot3_s <- d_skeptic_wide %>% 
  ggplot(aes(x = v3, color = group))+
  geom_density()

plot4_s <- d_skeptic_wide %>% 
  ggplot(aes(x = v4, color = group))+
  geom_density()

plot5_s <- d_skeptic_wide %>% 
  ggplot(aes(x = v5, color = group))+
  geom_density()

plot6_s <- d_skeptic_wide %>% 
  ggplot(aes(x = v6, color = group))+
  geom_density()

plot7_s <- d_skeptic_wide %>% 
  ggplot(aes(x = v7, color = group))+
  geom_density()

plot8_s <- d_skeptic_wide %>% 
  ggplot(aes(x = v8, color = group))+
  geom_density()

plot9_s <- d_skeptic_wide %>% 
  ggplot(aes(x = v9, color = group))+
  geom_density()

plot10_s <- d_skeptic_wide %>% 
  ggplot(aes(x = v10, color = group))+
  geom_density()

cowplot::plot_grid(plot1_s, plot2_s, plot3_s, plot4_s, plot5_s, plot6_s, plot7_s, plot8_s, plot9_s, plot10_s, 
          labels = c("v1", "v2", "v3",'v4','v5','v6','v7','v8','v9','v10'),
          ncol = 5, nrow = 2)


```

```{r}
##Machine Learning pipeline
TestID <- sample(seq(n),20)

train_informed <- d_informed_wide %>%
  subset(!(ID%in% TestID))
test_informed <- d_informed_wide %>% subset(ID%in%TestID)

train_skeptic <- d_skeptic_wide %>%
  subset(!(ID%in% TestID))
test_skeptic <- d_skeptic_wide %>% subset(ID%in%TestID)

##Splitting the data using stratified, which also take into consideration stratification of the f.e. gender

# set.seed(666)
# stratified(d_informed_wide, "Group", 0.8)
# 
# ?stratified


#Scaling
rec_informed <- train_informed %>% 
  recipe(Group~.) %>% 
  step_scale(all_numeric()) %>% 
  step_center(all_numeric()) %>% 
  prep(train_informed, retain=TRUE)

rec_skeptic <- train_skeptic %>% 
  recipe(Group~.) %>% 
  step_scale(all_numeric()) %>% 
  step_center(all_numeric()) %>% 
  prep(train_skeptic, retain=TRUE)

train_informed_s <- juice(rec_informed)
test_informed_s <- bake(rec_informed, new_data = test_informed)

train_skeptic_s <- juice(rec_skeptic)
test_skeptic_s <- bake(rec_skeptic, new_data = test_skeptic)

#Ask ricardo about the ID scaling
```

```{r}
#Plotting
ggplot(train_informed, aes(V2, Group, colour=Group))+
  geom_point()+
  geom_smooth(method = "glm", se=FALSE)+
  theme_bw()

ggplot(train_informed)+
  geom_histogram(aes(V2, fill= Group))

ggplot(train_skeptic)+
  geom_histogram(aes(V2, fill= Group))

#Make the distribution 
```
```{r}
##Setting up the model
PR_f0 <-bf(Group~1+V2)

get_prior(PR_f0, train_informed, family = bernoulli)
```
```{r}
##setting the priors
PR_p0 <- c(
  prior(normal(0,1), class=Intercept),
  prior(normal(0, 0.3), class=b)
)
```

```{r}
##Model
PR_m0 <- brm(
  PR_f0,
  train_informed,
  family=bernoulli,
  prior = PR_p0,
  sample_prior = T,
  backend = "cmdstanr",
  chains = 2,
  cores=2,
  threads = threading(2),
  control = list(adapt_delta=0.9,
               max_treedepth=20),
  stan_model_args=list(stanc_options=list("01"))
)
```
```{r}
##Model interpretation
PR_m0

```

